#!/bin/bash

# Linux specific
alias pbcopy='xclip -selection clipboard'

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias -- -="cd -"

# Shortcuts
alias dl="cd ~/Downloads"
alias g="git"
alias h="history"
alias gc=". /usr/local/bin/gitdate && git commit -v "

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
	colorflag="-G"
fi

# List all files colorized in long format
# shellcheck disable=SC2139
alias l="ls -lhF ${colorflag}"

# List all files colorized in long format, including dot files
# shellcheck disable=SC2139
alias la="ls -lahF ${colorflag}"

# List only directories
# shellcheck disable=SC2139
alias lsd="ls -lhF ${colorflag} | grep --color=never '^d'"

# Always use color output for `ls`
# shellcheck disable=SC2139
alias ls="command ls ${colorflag}"
export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

# Oracle
alias sqlplus='rlwrap "${ORACLE_HOME}/bin/sqlplus"'
alias tns='sh -c "cat ${ORACLE_HOME}/network/admin/tnsnames.ora"'

# R - radian
alias r="radian"

# Elixir
alias phx.migrate="MIX_ENV=dev mix do ecto.migrate, ecto.dump && MIX_ENV=test mix do ecto.drop, ecto.create, ecto.load"

# Projects
alias ml="cd ~/Developer/Projects/marclambrichs"
alias 9to5="cd ~/Developer/Projects/marclambrichs/ninetofive"
alias elix="cd ~/Developer/Projects/elixir"

# DPG
alias dpg="cd ~/Developer/Projects/customers/dpgmediagroup/my-channels/mychannels-elixir-vaas"
alias mc_asset_api="cd /Users/mlambrichs/Developer/Projects/customers/dpgmediagroup/my-channels/mychannels-elixir-vaas/apps/mc_asset_api"
alias mc_core="cd /Users/mlambrichs/Developer/Projects/customers/dpgmediagroup/my-channels/mychannels-elixir-vaas/apps/mc_core"
alias mc_emma="cd /Users/mlambrichs/Developer/Projects/customers/dpgmediagroup/my-channels/mychannels-elixir-vaas/apps/mc_emma"
alias mc_io="cd /Users/mlambrichs/Developer/Projects/customers/dpgmediagroup/my-channels/mychannels-elixir-vaas/apps/mc_io"
alias mc_web="cd /Users/mlambrichs/Developer/Projects/customers/dpgmediagroup/my-channels/mychannels-elixir-vaas/apps/mc_web"
alias mc_world_api="cd /Users/mlambrichs/Developer/Projects/customers/dpgmediagroup/my-channels/mychannels-elixir-vaas/apps/mc_world_api"
alias aws.sso="aws sso login --profile dpg-administrator-cf"
alias dpg.test.tunnel="./dbssm.sh -d test -p 5001"
alias dpg.prod.tunnel="./dbssm.sh -d prod -p 5001"
alias dpg.acc.tunnel="./dbssm.sh -d acc -p 5001" 
