#!/bin/sh

# go path
export ASDFPATH=${HOME}/.asdf
export DOCKERPATH=${HOME}/.docker
export GOPATH=${HOME}/.go
export GOROOT=${HOME}/dev/github.com/goroot
export JULIAPATH=/usr/local/julia
export NODEPATH=${HOME}/.asdf/installs/nodejs/16.16.0
export PACKERPATH=${HOME}/dev/github/packer

# update path
export PATH=$HOME/bin:/usr/local/bin:${PATH}:/sbin

# add asdf path
export PATH="${ASDFPATH}/shims:${PATH}"

# add docker path
export PATH="${DOCKERPATH}/bin:${PATH}"

# add go path
export PATH="${GOROOT}/bin:${GOPATH}/bin:${PATH}"

# add java path
export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")

# add julia path
export PATH="${JULIAPATH}/bin:${PATH}"

# add node path
export PATH="${NODEPATH}/bin:${PATH}"

# add oracle
export ORACLE_HOME=~/.oracle
export LD_LIBRARY_PATH=${ORACLE_HOME}/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export PATH=$PATH:${ORACLE_HOME}/bin

# add packer path
export PATH="${PACKERPATH}/bin:${PATH}"

